### PR TITLE
minor changes Arch Linux installation

### PR DESCRIPTION
**Pull request by nedy13**

### CODE REVIEW

**Comment by onli** [comment]
I'll merge this. But I'll then change the pacman command to not be version dependant.

Btw, is it necessary to wget that file, can't pacman do that automatically?

**Comment by onli** [comment]
Btw, thanks again :)

**Comment by nedy13** [comment]
Arch Linux also has an User Repo like Ubuntu's PPA. It is called "AUR" (https://aur.archlinux.org/).
Then you are able to install izulu from a package management like "yaourt" (pacman + AUR).

This is my first package file I have ever created. I have never published an AUR package.

**Comment by onli** [comment]
Okay. If you ever feel up to it, that would be a great addition. But I'm already very happy about having the pkgbuild file in the first build, so please don't feel obliged.

**Pull request merged**
